Greeny467/terse_social_media

controllers/index.js
controllers/pageRoutes.js
models/index.js

Added pageRoutes routes for the different web pages.

Merging pageRoutes features

---

controllers/api/user-routes.js

Also changed name of first 'existingUser' var to 'newUser'

Added userId var to session

---

views/layouts/main.handlebars

Main Handlebar Template

---

controllers/pageRoutes.js
views/chat.handlebars
views/home.handlebars
views/inbox.handlebars
views/layouts/main.handlebars
views/login.handlebars
views/user.handlebars

Added a login pageRoute. Added basic view files with simple html for each web page needed. Made some structural changes to the main.handlebars layout.

Login pageRoute, basic view html, changes to main layout

---

public/js/chat.js
public/js/home.js
public/js/inbox.js
public/js/userpage.js
views/chat.handlebars
views/home.handlebars
views/inbox.handlebars
views/login.handlebars
views/user.handlebars

Created empty public.js files with directive comments. Linked said files to their respective views.

Adding some public.js files work 

---

controllers/pageRoutes.js
public/js/login.js
server.js
util/auth.js
views/home.handlebars
views/inbox.handlebars
views/layouts/main.handlebars

Created withAuth utility module. Added sign up function to login.js. Finalized login and signup capabilities. Made small changes to some handlebars views. Resolved some errors with the areThereChats variable on the home route. Website now has the functionality of sending the client view files and data, so we can now navigate the website itself and working with the app will be much easier.

Login functionality and website basics

---

controllers/pageRoutes.js
public/js/chat.js
server.js
views/chat.handlebars

Added message appending functionality to chat.js in the public folder. This populates the message area in the chat view with all the messages, each message having its respective author name, date, and text, as well as a class depending on whether the logged in user wrote it or the other user in the chat did, to allow us to mimic modern messaging page format.

Added message appending functionality

---

public/js/home.js
views/home.handlebars

Though it is missing its users array to pull from, the search bar generates links matching the users input on every key up, similar to autocomplete searchbar capabilities.

Created homepage user searchbar functionality

---

public/js/chat.js
views/chat.handlebars
views/login.handlebars

Added rough sketch for the CSS for chats

Added rough sketch for the CSS

---

controllers/api/data_routes.js
controllers/pageRoutes.js
models/chat.js
models/chatUser.js
models/index.js
models/message.js
public/js/chat.js
public/js/home.js
public/js/userpage.js
seeds/chatData.json
seeds/messageData.json
seeds/seed.js
seeds/userChatData.json
views/chat.handlebars
views/home.handlebars
views/user.handlebars

Got rid of user1 and user2 id values for chat, created a many to many relation for chat and User through a new ChatUser model. Changed seeding data to reflect these changes. Made changes to page routes to match these fixes. Got user pages running, but since the chat system is different, A new friend system has to be invented and a new chat creation system must be created too. In good news, this will allow for chats to be made with 3 or more users in them, and not just 2 person chats.

Changed chat relational structure, and more

---

controllers/pageRoutes.js
models/friendship.js
models/index.js
models/request.js
public/js/chat.js
seeds/friendship.json
seeds/requestData.json
seeds/seed.js
views/chat.handlebars
views/home.handlebars
views/layouts/main.handlebars

Created friendship model and relations, allowing for friendships to be made between users. Created data for friendship seeding. Changed handlebars views slightly. Added new link to user profile page (users own userpage) where friends and chats can be viewed. Added form on homepage to create new chats, with no functionality yet. Added basic structure for invite button pop out menu in the chat page, where a user can click on the invite user button to see their friend list and invite one of their friends to the chat. Included new User variable in chat view render with friends included.

Created friendship model and relations +public.js work

---

controllers/pageRoutes.js
public/js/userpage.js
seeds/friendship.json
seeds/messageData.json
seeds/requestData.json

Finished all userpage necessities for the mvp. Added ability to see all friends as well as chats from your own user page. Created better handling for showing requests on userpages.

Finished userpage.js and added other functionalities

---

controllers/api/data_routes.js
public/js/chat.js
public/js/messaging.js
views/chat.handlebars

Added functionality so that when the invite button is pressed in the chat view, a list of users which can be invited is given with buttons to send requests. There is a back button to remove this list. 
Added db post request in chat.js to send requests when the invite user button is pressed. 
Made some small changes to handlebars 
I've decided to migrate messaging functionality to a new file because the chat.js file is crowded. It has been properly linked.

Added functionality to invite users to chats

---

controllers/api/data_routes.js
public/js/messaging.js
views/chat.handlebars

Added basic messaging functionality in the messaging.js file.

Added Messaging!

---

public/js/home.js
public/js/messaging.js

Added functionality to create chats using home.js. The createChat function posts a new chat and then posts the client user as a new chatUser.

Added functionality to create Chats

---

public/js/checkInput.js
public/js/home.js
public/js/messaging.js
views/chat.handlebars
views/home.handlebars

User input is now limited to only one word. To do so we split their input at any spaces and take the first word. Then we make a fetch to the WordsAPI to check if the users input is a word. If it isn't, the user is sent an alert telling them their input was not a word. Otherwise, a new message or chat is created with their input. The api has a daily request limit of 2500 so keep that in mind.

Added one word restrictions!

---

controllers/api/data_routes.js
public/js/checkInput.js

API key was exposed before. Now it is a .env variable.

Added security for RAPID API key

---

controllers/api/data_routes.js

The POST request route had an issue in its req.body verification where values of zero in the inviteChat_id (The value it's supposed to be for a friendRequest) made the if statement return false.

Fixed minor issue in post request route

---

controllers/api/data_routes.js
public/js/chat.js

Added a findNewMessages function for the chat page which checks for new messages using a fetch to our own api and populates any on the screen. This function is run currently every 15 seconds, so new messages will populate the screen every fifteen seconds.

Added 'live' messaging functionality.

---

public/js/chat.js
views/chat.handlebars

Added proper materialize classes to put client user messages on the right side of the screen.

 Minor changes to css to include right side messages

---

public/js/userpage.js
views/user.handlebars

Fixed username centering. Fixed friends list display

Fixed userpage css

---

views/user.handlebars

On my machine it shows up properly but it doesn't on the deployed app. The username appears on the left in the userpage on the deployed version.

Trying to fix deployed app userpage css
